env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: ["error", "only-multiline"]
  func-call-spacing: ["error", "never"]
  space-before-function-paren: ["error", "never"]
  sort-imports: ["error", {
      "ignoreCase": true,
      "ignoreDeclarationSort": false,
      "ignoreMemberSort": false,
      "memberSyntaxSortOrder": ["none", "all", "multiple", "single"]
  }]
  strict: ["error", "global"]
  indent: ["error", 4]
  no-var: "error"
  padded-blocks: ["error", {'classes': 'always'}]
  semi: ["error", "always"]
